### ISSUE TITLE
order of execution

### ISSUE THREAD

**Issue by szymtor** [eryxcc/regnetsearch#3]
Currently, the order is as follows:

Reading the database...
Building the relations...
Parsing the expression...

The first two steps are long, the last one is short, and often results in an error.
I propose to first parse, then read and build.

**Comment by eryxcc** [comment]
Another added benefit -- no need to load parts of the database which are not used in the query.

This is currently done like this because some calculations are done during parsing, but a preliminary parsing stage would still be useful indeed.

**Comment by eryxcc** [comment]
Reading databases, regex/string searching, folding, and applying is now done lazily, and actually executed while constructing the automaton. This closes the issue.
