### ISSUE TITLE
connectives

### ISSUE THREAD

**Issue by szymtor** [eryxcc/regnetsearch#5]
It should be possible to provide a list of searchwords, e.g.
search paperTitle "VC-dimension" "algorithm",

and also to use connectives, e.g.
search paperTitle "VC" and not search paperTitle "VCSP".

**Comment by eryxcc** [comment]
It should be possible already, e.g. search paperTitle "VC-dimension" | search paperTitle "algorithm". There is no "not" operator defined yet, but you could use e.g. search paperTitle "VC" & (1-search paperTitle "VCSP") or search paperTitle "VC" > search paperTitle "VCSP".

**Comment by eryxcc** [comment]
Added the negation operator (! as in C). Also fixed a parser bug which made `search paperTitle "VC-dimension" | search paperTitle "algorithm"` not work without parentheses.
